<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVHVLGCI\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVHVLGCI/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVHVLGCI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVHVLGCI\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerVHVLGCI\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'VHVLGCI',
    'container.build_id' => '72fcde6d',
    'container.build_time' => 1548408953,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVHVLGCI');
