<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SjZfX2U' shared service.

return $this->privates['.service_locator.SjZfX2U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'booking' => array('privates', '.errored..service_locator.SjZfX2U.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.SjZfX2U": it references class "App\\Entity\\Booking" but no such service exists.'),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
));
