<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SIDv2FW' shared service.

return $this->privates['.service_locator.SIDv2FW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'pagination' => array('privates', 'App\\Service\\PaginationService', 'getPaginationServiceService.php', true),
    'repo' => array('privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService.php', true),
));
