<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6O60kE7' shared service.

return $this->privates['.service_locator.6O60kE7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'comment' => array('privates', '.errored..service_locator.6O60kE7.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.6O60kE7": it references class "App\\Entity\\Comment" but no such service exists.'),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
));
