<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AccountController::login' => array('privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true),
    'App\\Controller\\AccountController::profile' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AccountController::register' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\AccountController::updatePassword' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\AdController::create' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AdController::delete' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdController::edit' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdController::index' => array('privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true),
    'App\\Controller\\AdController::show' => array('privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true),
    'App\\Controller\\AdminAccountController::login' => array('privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true),
    'App\\Controller\\AdminAdController::delete' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdminAdController::edit' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdminAdController::index' => array('privates', '.service_locator.lIFg_qI', 'get_ServiceLocator_LIFgQIService.php', true),
    'App\\Controller\\AdminBookingController::delete' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\AdminBookingController::edit' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\AdminBookingController::index' => array('privates', '.service_locator.SIDv2FW', 'get_ServiceLocator_SIDv2FWService.php', true),
    'App\\Controller\\AdminCommentController::delete' => array('privates', '.service_locator.6O60kE7', 'get_ServiceLocator_6O60kE7Service.php', true),
    'App\\Controller\\AdminCommentController::edit' => array('privates', '.service_locator.6O60kE7', 'get_ServiceLocator_6O60kE7Service.php', true),
    'App\\Controller\\AdminCommentController::index' => array('privates', '.service_locator.7zQ24yQ', 'get_ServiceLocator_7zQ24yQService.php', true),
    'App\\Controller\\AdminDashboardController::index' => array('privates', '.service_locator.9NXKdXr', 'get_ServiceLocator_9NXKdXrService.php', true),
    'App\\Controller\\BookingController::book' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\BookingController::show' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\GameController::index' => array('privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true),
    'App\\Controller\\HomeController::home' => array('privates', '.service_locator.RUUfoyn', 'get_ServiceLocator_RUUfoynService.php', true),
    'App\\Controller\\UserController::index' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AccountController:login' => array('privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true),
    'App\\Controller\\AccountController:profile' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AccountController:register' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\AccountController:updatePassword' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\AdController:create' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AdController:delete' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdController:edit' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdController:index' => array('privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true),
    'App\\Controller\\AdController:show' => array('privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true),
    'App\\Controller\\AdminAccountController:login' => array('privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true),
    'App\\Controller\\AdminAdController:delete' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdminAdController:edit' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\AdminAdController:index' => array('privates', '.service_locator.lIFg_qI', 'get_ServiceLocator_LIFgQIService.php', true),
    'App\\Controller\\AdminBookingController:delete' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\AdminBookingController:edit' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\AdminBookingController:index' => array('privates', '.service_locator.SIDv2FW', 'get_ServiceLocator_SIDv2FWService.php', true),
    'App\\Controller\\AdminCommentController:delete' => array('privates', '.service_locator.6O60kE7', 'get_ServiceLocator_6O60kE7Service.php', true),
    'App\\Controller\\AdminCommentController:edit' => array('privates', '.service_locator.6O60kE7', 'get_ServiceLocator_6O60kE7Service.php', true),
    'App\\Controller\\AdminCommentController:index' => array('privates', '.service_locator.7zQ24yQ', 'get_ServiceLocator_7zQ24yQService.php', true),
    'App\\Controller\\AdminDashboardController:index' => array('privates', '.service_locator.9NXKdXr', 'get_ServiceLocator_9NXKdXrService.php', true),
    'App\\Controller\\BookingController:book' => array('privates', '.service_locator.0c_I6Iz', 'get_ServiceLocator_0cI6IzService.php', true),
    'App\\Controller\\BookingController:show' => array('privates', '.service_locator.SjZfX2U', 'get_ServiceLocator_SjZfX2UService.php', true),
    'App\\Controller\\GameController:index' => array('privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true),
    'App\\Controller\\HomeController:home' => array('privates', '.service_locator.RUUfoyn', 'get_ServiceLocator_RUUfoynService.php', true),
    'App\\Controller\\UserController:index' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
