<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbn2TdT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbn2TdT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKbn2TdT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKbn2TdT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKbn2TdT\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Kbn2TdT',
    'container.build_id' => '9d733376',
    'container.build_time' => 1548859659,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbn2TdT');
